package model;

public enum OrbitoModelStatus {
    PLAYER_MOVE_OR_PLACE_STONE,
    PLAYER_PLACE_STONE,
    PUSH_ORBITO_BUTTON,
    GAME_ENDED_SINGLE_PAYER_WON,
    GAME_ENDED_BOTH_PLAYERS_WON,
    GAME_ENDED_NO_STONES_LEFT
}
